# Generated by Django 5.0.4 on 2024-04-20 23:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('breakfast_calories', models.IntegerField(default=0)),
                ('breakfast_fat', models.IntegerField(default=0)),
                ('breakfast_carbs', models.IntegerField(default=0)),
                ('breakfast_protein', models.IntegerField(default=0)),
                ('lunch_calories', models.IntegerField(default=0)),
                ('lunch_fat', models.IntegerField(default=0)),
                ('lunch_carbs', models.IntegerField(default=0)),
                ('lunch_protein', models.IntegerField(default=0)),
                ('dinner_calories', models.IntegerField(default=0)),
                ('dinner_fat', models.IntegerField(default=0)),
                ('dinner_carbs', models.IntegerField(default=0)),
                ('dinner_protein', models.IntegerField(default=0)),
                ('breakfast_time', models.TimeField(blank=True, null=True)),
                ('lunch_time', models.TimeField(blank=True, null=True)),
                ('dinner_time', models.TimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
